# Generated by Django 4.2.23 on 2025-08-20 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('conversion_rate', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'إحصائيات يومية',
                'verbose_name_plural': 'الإحصائيات اليومية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('page_visited', models.CharField(default='/', max_length=200)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'سطح المكتب'), ('mobile', 'جوال'), ('tablet', 'تابلت'), ('unknown', 'غير معروف')], default='unknown', max_length=50)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('session_duration', models.PositiveIntegerField(default=0)),
                ('is_engaged', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'زائر',
                'verbose_name_plural': 'الزوار',
                'ordering': ['-last_visit'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=200)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='landing.visitor')),
            ],
            options={
                'verbose_name': 'مشاهدة صفحة',
                'verbose_name_plural': 'مشاهدات الصفحات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_clicked', models.CharField(choices=[('cta_primary', 'زر فتح الحساب الرئيسي'), ('cta_secondary', 'زر اكتشف خدماتنا'), ('cta_large', 'زر فتح الحساب الكبير'), ('social_telegram', 'رابط التليجرام'), ('social_whatsapp', 'رابط الواتساب'), ('social_instagram', 'رابط الانستجرام'), ('nav_services', 'رابط الخدمات في التنقل')], max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_url', models.CharField(default='/', max_length=200)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='landing.visitor')),
            ],
            options={
                'verbose_name': 'نقرة',
                'verbose_name_plural': 'النقرات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
