# Generated by Django 4.2.23 on 2025-08-23 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('service', models.CharField(blank=True, choices=[('strategy', 'إستراتيجية أبو صفية'), ('telegram', 'لايف على التليجرام'), ('internal-deals', 'صفقات داخلية'), ('mt5-connection', 'ربط حساب MT5'), ('', 'غير محدد')], max_length=20, verbose_name='الخدمة المطلوبة')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
    ]
