# Generated by Django 4.2.23 on 2025-08-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email_error',
            field=models.TextField(blank=True, null=True, verbose_name='خطأ البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='تم إرسال البريد'),
        ),
    ]
